---
- name: DISA STIG RHEL 9 — Headless Server
  hosts: servers
  become: true
  gather_facts: true

  vars_files:
    - ../vars/profiles/stig_defaults.yml

  vars:
    dconf_db_up_to_date:                    false  # no GNOME on server
    dconf_gnome_banner_enabled:             false
    dconf_gnome_disable_automount_open:     false
    dconf_gnome_disable_autorun:            false
    dconf_gnome_disable_ctrlaltdel_reboot:  false
    dconf_gnome_disable_restart_shutdown:   false
    dconf_gnome_disable_user_list:          false
    dconf_gnome_lock_screen_on_smartcard_removal: false
    dconf_gnome_login_banner_text:          false
    dconf_gnome_screensaver_idle_delay:     false
    dconf_gnome_screensaver_lock_delay:     false
    dconf_gnome_screensaver_lock_enabled:   false
    dconf_gnome_screensaver_mode_blank:     false
    dconf_gnome_screensaver_user_locks:     false
    dconf_gnome_session_idle_user_locks:    false
    gnome_gdm_disable_automatic_login:      false
    logind_session_timeout:                 false
    DISA_STIG_RHEL_09_271010: false  # dconf_gnome_screensaver_idle_delay (GUI)

  roles:
    - role: RedHatOfficial.rhel9_stig
    # NOTE: rhel9_stig_gui is intentionally NOT listed here

  tasks:
    - name: Run OpenSCAP after STIG application
      import_tasks: ../tasks/oscap_server.yml
