---
- name: DISA STIG RHEL 9 — Graphical Workstation
  hosts: workstations
  become: true
  gather_facts: true

  vars_files:
    - ../vars/profiles/stig_defaults.yml

  vars:

  roles:
    # This role is REQUIRED for a graphical workstation to meet DISA reqs
    - role: RedHatOfficial.rhel9_stig_gui

  tasks:
    - name: Include OpenSCAP scanning task
      import_tasks: ../tasks/oscap_workstation.yml
